
import { useState } from "react";
import { Card, CardContent, CardHeader, CardTitle, CardDescription, CardFooter } from "@/components/ui-custom/Card";
import { Button } from "@/components/ui-custom/Button";
import { Badge } from "@/components/ui-custom/Badge";
import { MessageSquare, CheckCircle, Copy, FileEdit, Trash2, Send } from "lucide-react";
import { useToast } from "@/hooks/use-toast";
import { AlertDialog, AlertDialogAction, AlertDialogCancel, AlertDialogContent, AlertDialogDescription, AlertDialogFooter, AlertDialogHeader, AlertDialogTitle } from "@/components/ui/alert-dialog";

export type MessageTemplateProps = {
  id: string;
  title: string;
  content: string;
  category: string;
  createdAt: string; // ISO date string
  usageCount?: number;
  model?: string; // AI model if generated by AI
  onEdit?: (id: string) => void;
  onDelete?: (id: string) => void;
  onUse?: (id: string, content: string) => void;
  showActions?: boolean; // Add this property to fix the build error
};

const MessageTemplate = ({ 
  id, 
  title, 
  content, 
  category, 
  createdAt, 
  usageCount = 0,
  model,
  onEdit,
  onDelete,
  onUse,
  showActions = true // Default to true for backward compatibility
}: MessageTemplateProps) => {
  const [showDeleteDialog, setShowDeleteDialog] = useState(false);
  const { toast } = useToast();
  
  const copyToClipboard = () => {
    navigator.clipboard.writeText(content);
    toast({
      title: "Copied to clipboard",
      description: "Message template copied to clipboard",
    });
  };
  
  const handleDelete = () => {
    setShowDeleteDialog(false);
    if (onDelete) {
      onDelete(id);
    }
  };
  
  const formatDate = (dateString: string) => {
    const date = new Date(dateString);
    return date.toLocaleDateString('en-US', { 
      month: 'short', 
      day: 'numeric', 
      year: 'numeric' 
    });
  };
  
  return (
    <>
      <Card className="h-full flex flex-col animate-fade-in">
        <CardHeader className="pb-3">
          <div className="flex justify-between items-start">
            <div>
              <CardTitle className="text-base">{title}</CardTitle>
              <CardDescription>{formatDate(createdAt)}</CardDescription>
            </div>
            <Badge variant="outline">{category}</Badge>
          </div>
        </CardHeader>
        <CardContent className="py-2 flex-1">
          <div className="bg-muted/30 p-3 rounded-md text-sm whitespace-pre-wrap min-h-[100px]">
            {content}
          </div>
          
          {model && (
            <div className="mt-3 flex items-center text-xs text-muted-foreground">
              <MessageSquare size={12} className="mr-1" />
              Generated with {model}
            </div>
          )}
          
          {usageCount > 0 && (
            <div className="mt-3 flex items-center text-xs text-muted-foreground">
              <CheckCircle size={12} className="mr-1" />
              Used {usageCount} time{usageCount !== 1 ? 's' : ''}
            </div>
          )}
        </CardContent>
        <CardFooter className="flex justify-between pt-3 border-t">
          {showActions ? (
            <>
              <div className="flex gap-1">
                <Button 
                  variant="ghost" 
                  size="sm"
                  onClick={copyToClipboard}
                  className="h-8 px-2"
                >
                  <Copy size={14} />
                </Button>
                {onEdit && (
                  <Button
                    variant="ghost"
                    size="sm"
                    onClick={() => onEdit(id)}
                    className="h-8 px-2"
                  >
                    <FileEdit size={14} />
                  </Button>
                )}
                {onDelete && (
                  <Button
                    variant="ghost"
                    size="sm"
                    onClick={() => setShowDeleteDialog(true)}
                    className="h-8 px-2 text-destructive"
                  >
                    <Trash2 size={14} />
                  </Button>
                )}
              </div>
              {onUse && (
                <Button
                  size="sm"
                  onClick={() => onUse(id, content)}
                >
                  <Send size={14} className="mr-1" />
                  Use
                </Button>
              )}
            </>
          ) : (
            <div className="flex justify-end w-full">
              {onUse && (
                <Button
                  size="sm"
                  onClick={() => onUse(id, content)}
                >
                  <Send size={14} className="mr-1" />
                  Use
                </Button>
              )}
            </div>
          )}
        </CardFooter>
      </Card>
      
      <AlertDialog open={showDeleteDialog} onOpenChange={setShowDeleteDialog}>
        <AlertDialogContent>
          <AlertDialogHeader>
            <AlertDialogTitle>Delete Template</AlertDialogTitle>
            <AlertDialogDescription>
              Are you sure you want to delete the template "{title}"? This action cannot be undone.
            </AlertDialogDescription>
          </AlertDialogHeader>
          <AlertDialogFooter>
            <AlertDialogCancel>Cancel</AlertDialogCancel>
            <AlertDialogAction onClick={handleDelete} className="bg-destructive text-destructive-foreground hover:bg-destructive/90">
              Delete
            </AlertDialogAction>
          </AlertDialogFooter>
        </AlertDialogContent>
      </AlertDialog>
    </>
  );
};

export default MessageTemplate;
