// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lhvkzcqdkrtdyqxfgbjo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imxodmt6Y3Fka3J0ZHlxeGZnYmpvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMyODQ5MTMsImV4cCI6MjA1ODg2MDkxM30.fw3ZW9UE8Pq9AQrkTZ8EtDPiCBzQ3mTwppH1LJIlNTg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);